### Get all users
GET http://localhost:3000/api/v1/users
Accept: application/json

### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "seaeaes",
  "email": "john.doe@example.com"
}

### Get a user by ID
GET http://localhost:3000/api/v1/users/b94bd40b-5bd8-4aec-b741-d499c2be0393
Accept: application/json

### Update a user
PUT http://localhost:3000/api/v1/users/b94bd40b-5bd8-4aec-b741-d499c2be0393
Content-Type: application/json

{
  "name": "Galanx",
  "email": "jane.doe@example.com"
}

### Delete a user
DELETE http://localhost:3000/api/v1/users/b94bd40b-5bd8-4aec-b741-d499c2be0393

### Get All Transactions
GET http://localhost:3000/api/v1/transactions
Content-Type: application/json

### Create a New Transaction
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
  "type": "pemasukan",
  "amount": 1500000,
  "description": "Gaji bulanan",
  "category": "gaji",
  "userId": "user_id_here" // Ganti dengan ID user yang valid
}


### Get Transaction by ID
GET http://localhost:3000/api/v1/transactions/transaction_id_here
Content-Type: application/json

###

### Update Transaction
PUT http://localhost:3000/api/v1/transactions/transaction_id_here
Content-Type: application/json

{
  "type": "pengeluaran",
  "amount": 500000,
  "description": "Belanja bulanan",
  "category": "belanja"
}

###

### Delete Transaction
DELETE http://localhost:3000/api/v1/transactions/transaction_id_here
Content-Type: application/json
